export interface Provider {
  id: number;
  solvencia: string;
  nombreComercial: string;
  razonSocial: string;
  ruc: string;
  contacto: string;
  telefono: string;
  correo: string;
  departamento: string;
  direccion: string;
  sector: string;
  subsector: string;
}

export const providers: Provider[] = [
  {
    id: 1,
    solvencia: '2025-06-29',
    nombreComercial: 'Expósito-Raya',
    razonSocial: 'Gárate-Verdú S.A.C.',
    ruc: '94864737724',
    contacto: 'test',
    telefono: '+34646 89 92 57',
    correo: 'edmundoagudo@yahoo.com',
    departamento: 'Málaga',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 2,
    solvencia: '2025-08-21',
    nombreComercial: 'Cardona, Zorrilla and Hernandez',
    razonSocial: 'Becerra, Quevedo and Domingo S.A.C.',
    ruc: '20211042016',
    contacto: 'test',
    telefono: '+34 724 87 74 10',
    correo: 'cfrutos@amat.com',
    departamento: 'Las Palmas',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 3,
    solvencia: '2026-01-26',
    nombreComercial: 'Terrón Group',
    razonSocial: 'Barroso, Cazorla and Pedraza S.A.C.',
    ruc: '82392078395',
    contacto: 'test',
    telefono: '+34 967 50 17 25',
    correo: 'clara38@aznar.es',
    departamento: 'Ávila',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 4,
    solvencia: '2027-05-28',
    nombreComercial: 'Rivero, Martínez and Acero',
    razonSocial: 'Arroyo Inc S.A.C.',
    ruc: '61518160387',
    contacto: 'test',
    telefono: '+34728 91 10 83',
    correo: 'zuritajose-luis@camara-oller.net',
    departamento: 'Sevilla',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 5,
    solvencia: '2027-02-11',
    nombreComercial: 'Gomila, Dávila and Salas',
    razonSocial: 'Exposito, Cózar and Cánovas S.A.C.',
    ruc: '47016860842',
    contacto: 'test',
    telefono: '+34960 94 90 14',
    correo: 'merchevargas@corominas.org',
    departamento: 'Jaén',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 6,
    solvencia: '2026-06-13',
    nombreComercial: 'Vives, Agustí and Peláez',
    razonSocial: 'Borrego, Sola and Osuna S.A.C.',
    ruc: '41596552285',
    contacto: 'test',
    telefono: '+34734819307',
    correo: 'roperoisidora@hurtado-colom.com',
    departamento: 'Valencia',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 7,
    solvencia: '2026-09-03',
    nombreComercial: 'Piñeiro-Bas',
    razonSocial: 'Arenas Ltd S.A.C.',
    ruc: '24668593839',
    contacto: 'test',
    telefono: '+34 813 416 726',
    correo: 'cabrerojoan@hotmail.com',
    departamento: 'León',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 8,
    solvencia: '2026-12-06',
    nombreComercial: 'Moliner-Villalba',
    razonSocial: 'Alfaro, Álamo and Arjona S.A.C.',
    ruc: '92594781828',
    contacto: 'test',
    telefono: '+34948 880 341',
    correo: 'hernando03@hotmail.com',
    departamento: 'Ciudad',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 9,
    solvencia: '2026-04-29',
    nombreComercial: 'Vila Inc',
    razonSocial: 'Cuenca-Fuente S.A.C.',
    ruc: '65854141233',
    contacto: 'test',
    telefono: '+34 741324399',
    correo: 'melchor89@salva-blazquez.es',
    departamento: 'Jaén',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 10,
    solvencia: '2026-12-28',
    nombreComercial: 'Cuenca-Armas',
    razonSocial: 'Collado, Vallés and Heras S.A.C.',
    ruc: '80756680707',
    contacto: 'test',
    telefono: '+34723403249',
    correo: 'carrionfebe@fuentes.com',
    departamento: 'Navarra',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 11,
    solvencia: '2027-01-26',
    nombreComercial: 'Catalá-Álvaro',
    razonSocial: 'Velasco-Roldan S.A.C.',
    ruc: '41769690181',
    contacto: 'test',
    telefono: '+34831924499',
    correo: 'peracandelario@hotmail.com',
    departamento: 'Cádiz',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 12,
    solvencia: '2027-05-23',
    nombreComercial: 'Porcel, Barranco and Escudero',
    razonSocial: 'Portillo Ltd S.A.C.',
    ruc: '30659115423',
    contacto: 'test',
    telefono: '+34 735 74 69 44',
    correo: 'valenciapurificacion@yahoo.com',
    departamento: 'Zaragoza',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 13,
    solvencia: '2027-08-01',
    nombreComercial: 'Perales-Planas',
    razonSocial: 'España-Pérez S.A.C.',
    ruc: '54068217720',
    contacto: 'test',
    telefono: '+34 706 895 484',
    correo: 'iriarteeusebia@hotmail.com',
    departamento: 'Teruel',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 14,
    solvencia: '2026-11-22',
    nombreComercial: 'Camino-Blanco',
    razonSocial: 'Cuervo and Sons S.A.C.',
    ruc: '59264100445',
    contacto: 'test',
    telefono: '+34 715 837 132',
    correo: 'ufalco@gomez-rossello.es',
    departamento: 'Álava',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 15,
    solvencia: '2026-04-24',
    nombreComercial: 'Lledó-Cepeda',
    razonSocial: 'Herrera Group S.A.C.',
    ruc: '64464341942',
    contacto: 'test',
    telefono: '+34716 43 00 59',
    correo: 'abelvilla@cervantes.net',
    departamento: 'Santa Cruz de Tenerife',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 16,
    solvencia: '2027-05-31',
    nombreComercial: 'Márquez, Cámara and Guzman',
    razonSocial: 'Pedrero Ltd S.A.C.',
    ruc: '35187484710',
    contacto: 'test',
    telefono: '+34 735 08 61 49',
    correo: 'yanton@sosa-salas.net',
    departamento: 'Guipúzcoa',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 17,
    solvencia: '2026-08-14',
    nombreComercial: 'Peralta PLC',
    razonSocial: 'Morell-Capdevila S.A.C.',
    ruc: '13463954613',
    contacto: 'test',
    telefono: '+34722 482 523',
    correo: 'bbenitez@yahoo.com',
    departamento: 'Albacete',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 18,
    solvencia: '2027-01-21',
    nombreComercial: 'Cerro-Portero',
    razonSocial: 'Antúnez-Palau S.A.C.',
    ruc: '43963855757',
    contacto: 'test',
    telefono: '+34 715 348 004',
    correo: 'epalomo@bonilla.es',
    departamento: 'Jaén',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 19,
    solvencia: '2026-08-09',
    nombreComercial: 'Mendizábal, Heras and Osuna',
    razonSocial: 'Camino and Sons S.A.C.',
    ruc: '35648296610',
    contacto: 'test',
    telefono: '+34602 68 09 54',
    correo: 'fabricio69@hotmail.com',
    departamento: 'Barcelona',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
  {
    id: 20,
    solvencia: '2027-08-06',
    nombreComercial: 'Bautista-Almazán',
    razonSocial: 'Ibañez Group S.A.C.',
    ruc: '87838332271',
    contacto: 'test',
    telefono: '+34 746 473 295',
    correo: 'ncanizares@canet.net',
    departamento: 'La Coruña',
    direccion: 'test',
    sector: 'test',
    subsector: 'test',
  },
];
